# Generated by Django 2.2 on 2019-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191022_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('a', 'Активный'), ('f', 'Заморожен'), ('c', 'Завершенный')], max_length=5),
        ),
    ]
