# Generated by Django 2.2 on 2019-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191022_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('a', 'Активный'), ('c', 'Завершенный'), ('f', 'Заморожен')], max_length=5),
        ),
    ]
