# Generated by Django 2.2 on 2019-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191022_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('f', 'Заморожен'), ('a', 'Активный'), ('c', 'Завершенный')], max_length=5),
        ),
    ]
