# Generated by Django 2.2 on 2019-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191025_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('f', 'Заморожен'), ('c', 'Завершенный'), ('a', 'Активный')], max_length=5),
        ),
    ]
