# Generated by Django 2.2 on 2019-10-15 10:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_profile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_of_project', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('percent_of_user', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('user_role', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_projects', to='project.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, validators=[user_profile.validators.validate_number])),
                ('telegram', models.URLField()),
                ('status', models.CharField(choices=[('p', 'PM'), ('m', 'Ментор'), ('t', 'Тимлид'), ('h', 'HQ'), ('n', 'Новичок')], max_length=5)),
                ('congestion', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('validation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('resume', models.FileField(upload_to='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='department.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_plan', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('test', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
