# Generated by Django 2.2 on 2020-03-30 19:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Number in format: +996555111222', regex='^[+996][0-9]{12,12}$')])),
                ('telegram', models.URLField(null=True)),
                ('status', models.CharField(choices=[('h', 'HQ'), ('m', 'Ментор/Новичок')], max_length=5)),
                ('congestion', models.PositiveSmallIntegerField(blank=True, choices=[(100, 'Очень загружен'), (25, 'Немного занят'), (50, 'Частично занят'), (0, 'Свободен'), (75, 'Загружен')], null=True)),
                ('validation_code', models.CharField(blank=True, max_length=4, null=True)),
                ('summary', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='department.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_plan', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('out_of', models.PositiveSmallIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='user_profile.UserProfile')),
            ],
        ),
    ]
