# Generated by Django 2.2 on 2020-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='congestion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(50, 'Частично занят'), (0, 'Свободен'), (25, 'Немного занят'), (75, 'Загружен'), (100, 'Очень загружен')], null=True),
        ),
    ]
