# Generated by Django 2.2 on 2019-10-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('m', 'Ментор'), ('n', 'Новичок'), ('p', 'PM'), ('h', 'HQ'), ('t', 'Тимлид')], max_length=5),
        ),
    ]
