# Generated by Django 2.2 on 2019-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20191015_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('t', 'Тимлид'), ('n', 'Новичок'), ('h', 'HQ'), ('p', 'PM'), ('m', 'Ментор')], max_length=5),
        ),
    ]
