# Generated by Django 2.2 on 2019-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20191015_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('t', 'Тимлид'), ('n', 'Новичок'), ('m', 'Ментор'), ('p', 'PM'), ('h', 'HQ')], max_length=5),
        ),
    ]
