# Generated by Django 2.2 on 2019-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20191022_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('p', 'PM'), ('m', 'Ментор'), ('n', 'Новичок'), ('t', 'Тимлид'), ('h', 'HQ')], max_length=5),
        ),
    ]
