# Generated by Django 2.2 on 2019-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20191022_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('m', 'Ментор'), ('p', 'PM'), ('t', 'Тимлид'), ('n', 'Новичок'), ('h', 'HQ')], max_length=5),
        ),
    ]
