# Generated by Django 2.2 on 2019-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20191022_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('t', 'Тимлид'), ('n', 'Новичок'), ('h', 'HQ'), ('m', 'Ментор'), ('p', 'PM')], max_length=5),
        ),
    ]
