# Generated by Django 2.2 on 2019-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20191025_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('h', 'HQ'), ('n', 'Новичок'), ('m', 'Ментор'), ('t', 'Тимлид'), ('p', 'PM')], max_length=5),
        ),
    ]
