# Generated by Django 2.2 on 2019-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20191025_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('p', 'PM'), ('m', 'Ментор'), ('t', 'Тимлид'), ('n', 'Новичок'), ('h', 'HQ')], max_length=5),
        ),
    ]
